### ISSUE TITLE
format and name file is not as defined in functional document

### ISSUE THREAD

**Issue by Japoivvb** [TheSky189/DAM2_M06_UF1#2]
https://github.com/TheSky189/DAM2_M06_UF1/blob/2c0a4df51f9d0633243314dc7621ffc4362b0bb5/files/outputInventory.txt#L1

**Comment by TheSky189** [comment]
modified DaoImplFile, change function about generate output file and formatter.
        	// generar archivo con formato inventory_yyyy-mm-dd.txt
        	String date = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        	FileWriter writer = new FileWriter("files/inventory_" + date + ".txt");
