### ISSUE TITLE
there is not UT to verify this code works, e.g. it could be printed on console 

### ISSUE THREAD

**Issue by Japoivvb** [TheSky189/DAM2_M06_UF1#4]
https://github.com/TheSky189/DAM2_M06_UF1/blob/2c0a4df51f9d0633243314dc7621ffc4362b0bb5/src/dao/DaoImplFile.java#L13

**Comment by TheSky189** [comment]
Añadir Carpeta test; clic derecho en DaoImplFileTest.java y Ejecutar con JUnit para verificar la funcionalidad del método getInventory.
